### ISSUE TITLE
Killed

### ISSUE THREAD

**Issue by sxiii** [zupzup/warp-upload-download-example#2]
Hi!

Thanks for the nice example. First of all, it works for me with small PNG images. 

However! I'm trying to test out this example with larger files. I've bumped up the upload file size limit to 14 GB, and I'd like to do a test upload with that.

However, upon transferring about 1 GB of data, server drops down with message "Killed". I'm thinking it's getting killed either because it cannot calculate file size, or due to timeout, or both. Or another reason could be not enough RAM on the host, as I don't think it writes the file directly to the disk.

How can I prolong the waiting time and also write file directly to the disk, so it will accept large files like 15 GB or 100 GB?

I'll try to look into upstream documentation but maybe you could help me here.

Thanks

Den

**Comment by zupzup** [comment]
Hey Den

Hmm...interesting. The issue seems to be upstream, so maybe creating a ticket like this on https://github.com/seanmonstar/warp would make the most sense, since I never looked into this in any more detail than shown in this example.

Best,
Mario
