### ISSUE TITLE
Example fails with ""failed to lock multipart state"" , suggesting an update.

### ISSUE THREAD

**Issue by xana-b** [zupzup/warp-upload-download-example#3]
I tried your example with newer and would get a "failed to lock multipart state" error. 
This may be a breaking change in a new version of a crate. I use :
[package]
name = "dlt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.7.2"
futures = "0.3.30"
tokio = { version = "1.40", features = ["macros", "fs", "rt-multi-thread"] }
uuid = "1.10.0"
warp = "0.3.7"

Now I solved the issue by following the example from stackoverflow:
https://stackoverflow.com/questions/76290378/how-can-i-post-and-save-a-photo-using-rust-warp-multipart

I just wanted to let you know that you should maybe update the example since it is one of the most prominent google search results when looking for "warp multipart upload".

**Comment by zupzup** [comment]
Hey, thank you for making me aware of this. I fixed the example.
